"""Replace Column  with db.Column

Revision ID: 16e8ff5f59ed
Revises: 8c6f51fb1681
Create Date: 2024-01-16 16:26:05.856003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e8ff5f59ed'
down_revision: Union[str, None] = '8c6f51fb1681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
