"""add limit for Photoshoot and defoult date in Photographer

Revision ID: 70ba5c6536d6
Revises: 16e8ff5f59ed
Create Date: 2024-01-20 16:45:22.554040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ba5c6536d6'
down_revision: Union[str, None] = '16e8ff5f59ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photoshoots', sa.Column('limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photoshoots', 'limit')
    # ### end Alembic commands ###
